fix: useSubscription handles prop changes
nearform/graphql-hooks pull request #1105
Opened 2023-07-28 14:50 UTC by matt-clarson

### What does this PR do?

Adds the `useSubscription` options to the internal `useEffect` dependency array, so that changing the options triggers dropping and recreating a subscription using the new options
One important caveat is adding a custom equality check for the `options.variables` object, to avoid resubscribing when an object equivalent is recreated between renders, e.g.:

```javascript
const MyCoolComponent = () => {
    const [myVar, setMyVar] = useState(123)

    // `variables` here references a different object each rerender,
    // which could cause some fun problems when used with
    // useEffect's dependency array, which uses Object.is to determine equality
    const variables = {myVar}

    useSubscription({query: MY_QUERY, variables}, (...args) => {
        // do stuff
    })
}
```

Other approaches that would work instead of this:
 - Documenting the behaviour outlined in #1094 and including a note in the docs to store the entire variables object in state to avoid `Object.is` issues
 - Something like the [query key concept used by TanStack Query](https://tanstack.com/query/v3/docs/react/guides/query-keys)? 

### Related issues

Closes #1094 

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [x] I have added or updated any relevant documentation
- [x] I have added or updated any relevant tests

2023-08-16 15:23 UTC, Puppo requested changes

2023-08-16 15:23 UTC, Puppo commented on packages/graphql-hooks/src/useSubscription.ts
> +function isEqual(o1: object, o2: object): boolean {
I'd suggest moving this function in the `packages/graphql-hooks/src/utils.ts` file.

2023-08-16 15:23 UTC, Puppo commented on packages/graphql-hooks/test-jsdom/unit/useSubscription.test.tsx
> +        request: {query, variables: deepClone(variables)}
We can refactor using [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) and remove the deepClone implementation. The CI uses the node lts version, so I don't see any problems on using it.
```ts
        request: {query, variables: structuredClone(variables)}
```

2023-08-17 09:04 UTC, Puppo approved these changes

2023-08-17 09:40 UTC, simoneb reviewed
I'd recommend that we use this approach instead https://github.com/kentcdodds/use-deep-compare-effect

2023-08-17 15:22 UTC, Puppo commented
@simoneb I did the refactor. I noticed that something similar already existed with `useDeepCompareCallback`. So I used your tip about `use-deep-compare-effect` to develop our custom effect hook. Then I refactored the code to share the `useDeepCompareMemoize` in `useDeepCompareEffect` and `useDeepCompareCallback`. I also added tests to cover the new functions.
I'm unsure if adding the refactor in this PR is okay or if creating a new one is better; please, let me know your thoughts. In case splitting the code into two PRs is not a big deal.

2023-08-17 15:59 UTC, simoneb reviewed
is there another place in the code where we're using our own implementation? if so, I would replace that usage as well

2023-08-18 10:37 UTC, simoneb approved these changes
LGTM 🚀

2023-08-18 10:53 UTC, merged