feat: [WIP] add fullWsTransport support
nearform/graphql-hooks pull request #767
Opened 2022-01-18 13:04 UTC by nuragic

Add support for sending queries and mutations via WS, as proposed in [this issue](https://github.com/nearform/graphql-hooks/issues/766).

Tests are passing and I haven't touched them, so I think it's a good sign because this is not intended to be a breaking change. 😄 

### Next steps
- [ ] validate proposal
- [ ] add tests

Close #766.

2022-01-19 08:44 UTC, nuragic commented
This branch can be tested with this client: https://github.com/nuragic/graphql-react-app/blob/graphql-hooks/

It involves some `npm link`_ing_ but it's fine 🔗 📦 🙃 

The only missing thing on that demo app is the manual cache update, but I opened another issue for that: #768

2022-01-20 08:41 UTC, simoneb commented
Overall looks good so far, what's missing in this PR?

2022-01-20 08:49 UTC, simoneb commented
Resolve the todo and write documentation, yes. Shall we have an example showing how to use this feature, too?

2022-01-20 08:51 UTC, nuragic commented
Ok, I'll also add an example.

2022-02-08 12:08 UTC, krisgrint reviewed
Hi @nuragic just two tiny things with regard to the example app

2022-02-08 12:29 UTC, nuragic commented
@krisgrint Thanks for the review! Just fixed those right now.

2022-02-08 13:22 UTC, krisgrint approved these changes
LGTM!

2022-02-10 13:42 UTC, hails approved these changes

2022-02-10 14:10 UTC, simoneb requested changes
@hails a couple of comments, can you please address them?

2022-02-10 14:10 UTC, simoneb commented on packages/graphql-hooks/src/GraphQLClient.js
> +    } else {
redundant else

2022-02-10 14:10 UTC, simoneb commented on packages/graphql-hooks/src/GraphQLClient.js
> +      } else {
redundant else

2022-02-10 15:25 UTC, simoneb approved these changes

2022-02-10 15:26 UTC, merged